language: erlang
notifications:
  email:
    - engineering@2600hz.com
    - operations@2600hz.com
  irc:
    channels:
      - "irc.freenode.org#2600hz-dev"

otp_release:
  - 17.4
  - 17.3
  - 17.1
  - R16B03
  - R16B02
  - R16B01
  - R16B
  - R15B03

before_install:
  - set -e
  - sudo apt-get install -qq xsltproc
  - cd $HOME
  - git clone --depth=50 --branch=master https://github.com/manopapad/proper.git proper
  - cd proper
  - make fast
  - cd $TRAVIS_BUILD_DIR

script: make compile

after_success:
  - make xref
  - kerl_deactivate
  - source $HOME/otp/17.4/activate
  - make build-plt
  - git fetch origin master:master
  - files="$(git diff --name-only master.. | grep -v deps/)"
  - $TRAVIS_BUILD_DIR/scripts/check-dialyzer.escript $files
  - kerl_deactivate
  - source $HOME/otp/$TRAVIS_OTP_RELEASE/activate
  - ERL_LIBS="$HOME/proper" make test
